# Generated by Django 5.0.2 on 2024-03-01 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_date_mark_alter_bet_date_mark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='auction',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='person'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='auction',
            field=models.ManyToManyField(blank=True, to='auctions.auction'),
        ),
    ]
