# Generated by Django 5.0.2 on 2024-03-01 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_wishlist_auction_alter_wishlist_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='person'),
        ),
    ]
